### ISSUE TITLE
add an option to specify the timeout

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmspkg#3]
hi @smuzaffar ,
would you consider adding an option to`cmspkg.py` to specify the timeout passed to `curl`/`wget` ?

And/or increasing the timeout on retry ?

On a slow link (e.g. over an 1 MB/s ADSL) I regularly hit the timeout while downloading some of the large externals :-(

**Comment by smuzaffar** [comment]
sure, I will add option for this in next update

**Comment by smuzaffar** [comment]
@fwyzard,  with latest cmspkg you can use -o|--download-options  to pass extra options to curl/wget 
e.g. --download-options '--max-time 3600'
